---
# playbook file

- name: Test role
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true
  become: true
  tasks:
    - name: Check registration status
      command: subscription-manager identity
      register: registration_output
      ignore_errors: true

    - name: Display registration status
      debug:
        var: registration_output.rc
...

